"""
Generate opening book for Togyzkumalak.

Walks the first N plies of the game tree, runs deep alpha-beta on each
visited position, and records the best move(s). Output is a Python dict
keyed by full state hash that you paste into ai.py.

Usage:
    python generate_opening_book.py                    # default: 4 plies, 5s/move
    python generate_opening_book.py --depth 6 --time 8 # deeper and slower

The result replaces the existing OPENING_BOOK and switches its key from
(sum, currentPlayer) to a full state key.
"""
import argparse
import time
from collections import deque

from game_logic import TogyzkumalakState
from ai import get_best_move_alphabeta, _state_key, order_moves


def collect_positions(max_plies: int):
    """BFS through the game tree, returning unique positions reachable in <= max_plies."""
    seen = {}
    queue = deque()
    root = TogyzkumalakState()
    queue.append((root, 0))
    seen[_state_key(root)] = root

    while queue:
        state, ply = queue.popleft()
        if ply >= max_plies or state.isGameOver:
            continue
        for move in state.getPossibleMoves(state.currentPlayer):
            child = state.clone()
            child.makeMove(move)
            k = _state_key(child)
            if k not in seen:
                seen[k] = child
                queue.append((child, ply + 1))
    return seen


def best_moves_for(state: TogyzkumalakState, time_per_move: float, eps: float = 5.0):
    """Run alpha-beta and return the chosen move; we treat moves within `eps` of the best as ties."""
    move = get_best_move_alphabeta(state, state.currentPlayer, max_time_seconds=time_per_move)
    return [move]


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--depth", type=int, default=4, help="how many plies deep to expand the book")
    p.add_argument("--time", type=float, default=5.0, help="seconds per alpha-beta search")
    p.add_argument("--out", default="opening_book.py", help="output file with Python dict literal")
    args = p.parse_args()

    print(f"[gen] collecting positions up to {args.depth} plies deep...")
    positions = collect_positions(args.depth)
    print(f"[gen] found {len(positions)} unique positions")

    book = {}
    started = time.time()
    for i, (key, state) in enumerate(positions.items(), 1):
        elapsed = time.time() - started
        eta = elapsed / i * (len(positions) - i) if i else 0
        print(f"  [{i}/{len(positions)}] thinking... (elapsed {elapsed:.0f}s, eta {eta:.0f}s)", flush=True)
        moves = best_moves_for(state, args.time)
        book[key] = moves

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("# Auto-generated by generate_opening_book.py — do not edit by hand.\n")
        fh.write("# Paste this into ai.py to replace the existing OPENING_BOOK.\n")
        fh.write("OPENING_BOOK = {\n")
        for key, moves in book.items():
            fh.write(f"    {key!r}: {moves!r},\n")
        fh.write("}\n")

    print(f"[done] wrote {len(book)} entries to {args.out}")
    print(f"[done] total time: {time.time() - started:.0f}s")


if __name__ == "__main__":
    main()
